version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 406990755276.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker Image
      - docker build -t pythonwebapp .
      - docker tag pythonwebapp:latest 406990755276.dkr.ecr.ap-south-1.amazonaws.com/pythonwebapp:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 406990755276.dkr.ecr.ap-south-1.amazonaws.com/pythonwebapp:latest
